parameters:
#    dw_cache.example.class: DW\CacheBundle\Example

services:
#    dw_cache.example:
#        class: %dw_cache.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
